spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/demo
    username: root
    password: root
    driverClassName: org.postgresql.Driver